swagger: "2.0"
info:
  title: api Wowless API
  version: 0.0.1
basePath: /v0
schemes:
- https
paths:
  /moo:
    get:
      operationId: getMoo
      x-google-backend:
        address: https://wowless-pxnmni7wma-uc.a.run.app/wowless?product=wow_classic_era
      responses:
        200:
          description: OK
